In [3]:
import pandas as pd

In [8]:
df = pd.read_csv(r"xlf.csv", skiprows=1)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73 entries, 0 to 72
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Symbol         73 non-null     object
 1   Company Name   73 non-null     object
 2   Index Weight   73 non-null     object
 3   Last           73 non-null     float64
 4   Change         73 non-null     float64
 5   %Change        73 non-null     object
 6   Volume         73 non-null     object
 7   52 Week Range  73 non-null     object
dtypes: float64(2), object(6)
memory usage: 4.7+ KB

In [11]:
df.head(2)

,Symbol,Company Name,Index Weight,Last,Change,%Change,Volume,52 Week Range
0,BRK.b,Berkshire Hathaway B,11.91%,464.32,-4.36,-0.93%,2.44 M,381.48 - 491.67
1,JPM,JP Morgan Chase & Co,10.43%,267.28,-0.02,-0.01%,4.96 M,171.43 - 270.82

In [12]:
df.tail(2)

,Symbol,Company Name,Index Weight,Last,Change,%Change,Volume,52 Week Range
71,MKTX,MarketAxess Holdings,0.12%,220.41,-0.22,-0.10%,0.28 M,192.42 - 296.68
72,BEN,Franklin Resources Inc,0.10%,20.86,-1.39,-6.23%,5.93 M,18.83 - 28.61

In [22]:
df["IW_fl"] = df["Index Weight"].apply(lambda x : float(x.strip("%")))

In [31]:
av_weigt = round(df["IW_fl"].mean(),2)
av_weigt
f"Average weight of a stock in the index is {av_weigt}%"

'Average weight of a stock in the index is 1.37%'

In [32]:
# What is the total Volume?
df["Volume2"] = df["Volume"].apply(lambda x : float(x.strip(" M")))
df["Volume2"].sum()

167.12

In [35]:
df["Vol_fl"] = df["Volume"].str.strip("M").astype(float)

In [49]:
df
# how many stock have Last price less than 100 
df[df["Last"] < 100].count().iloc[0]

25

In [ ]:
# Get stock with the largest Last stock price

In [51]:
df[df["Last"]==df["Last"].max()][["Company Name","Last"]]

     Company Name     Last
10  BlackRock Inc  1021.56

In [55]:
df.sort_values("Last",ascending=False).iloc[0][["Company Name","Last"]]

Company Name    BlackRock Inc
Last                  1021.56
Name: 10, dtype: object

In [60]:
df.nlargest(3,"Last")[["Company Name","Last"]]
# help(df.nlargest)

               Company Name     Last
10            BlackRock Inc  1021.56
6   Goldman Sachs Group Inc   635.84
37                 MSCI Inc   584.82

In [61]:
df.nsmallest(3,"Last")[["Company Name","Last"]]

                  Company Name   Last
53  Huntington Bancshares (OH)  16.89
61                     KeyCorp  17.59
70                 Invesco Ltd  18.44

In [66]:
df[df["Company Name"].str.contains("Corp",case=False)].count().iloc[0]

18

In [67]:
df[df["Company Name"].str.contains("Group",case=False)].count().iloc[0]

11

In [74]:
df[["Low","High"]] = df["52 Week Range"].str.split("-", expand=True).astype(float)

In [76]:
df['Difference'] = df['High'] - df['Low']
df
# if last price less than 100 ---> buy else return Sell ---> apply and lambda

,Symbol,Company Name,Index Weight,Last,Change,%Change,Volume,52 Week Range,IW_fl,Volume2,Vol_fl,Low,High,Difference
0,BRK.b,Berkshire Hathaway B,11.91%,464.32,-4.36,-0.93%,2.44 M,381.48 - 491.67,11.91,2.44,2.44,381.48,491.67,110.19
1,JPM,JP Morgan Chase & Co,10.43%,267.28,-0.02,-0.01%,4.96 M,171.43 - 270.82,10.43,4.96,4.96,171.43,270.82,99.39
2,V,Visa Inc A,8.19%,345.35,3.55,+1.04%,4.63 M,252.70 - 351.25,8.19,4.63,4.63,252.70,351.25,98.55
3,MA,Mastercard Inc A,6.31%,563.83,8.40,+1.51%,1.65 M,428.86 - 576.94,6.31,1.65,1.65,428.86,576.94,148.08
4,BAC,Bank of America Corp,4.28%,46.29,-0.01,-0.03%,21.19 M,32.35 - 48.08,4.28,21.19,21.19,32.35,48.08,15.73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,GL,Globe Life Inc.,0.14%,122.04,-0.05,-0.04%,0.34 M,38.95 - 132.00,0.14,0.34,0.34,38.95,132.00,93.05
69,ERIE,Erie Indemnity Co A,0.14%,402.68,-0.27,-0.07%,0.12 M,337.58 - 547.00,0.14,0.12,0.12,337.58,547.00,209.42
70,IVZ,Invesco Ltd,0.12%,18.44,-0.79,-4.11%,3.13 M,14.16 - 19.55,0.12,3.13,3.13,14.16,19.55,5.39
71,MKTX,MarketAxess Holdings,0.12%,220.41,-0.22,-0.10%,0.28 M,192.42 - 296.68,0.12,0.28,0.28,192.42,296.68,104.26
72,BEN,Franklin Resources Inc,0.10%,20.86,-1.39,-6.23%,5.93 M,18.83 - 28.61,0.10,5.93,5.93,18.83,28.61,9.78

In [77]:
df["Buysell"] = df["Last"].apply(lambda x : "Buy" if x < 100 else "Sell")

df

,Symbol,Company Name,Index Weight,Last,Change,%Change,Volume,52 Week Range,IW_fl,Volume2,Vol_fl,Low,High,Difference,Buysell
0,BRK.b,Berkshire Hathaway B,11.91%,464.32,-4.36,-0.93%,2.44 M,381.48 - 491.67,11.91,2.44,2.44,381.48,491.67,110.19,Sell
1,JPM,JP Morgan Chase & Co,10.43%,267.28,-0.02,-0.01%,4.96 M,171.43 - 270.82,10.43,4.96,4.96,171.43,270.82,99.39,Sell
2,V,Visa Inc A,8.19%,345.35,3.55,+1.04%,4.63 M,252.70 - 351.25,8.19,4.63,4.63,252.70,351.25,98.55,Sell
3,MA,Mastercard Inc A,6.31%,563.83,8.40,+1.51%,1.65 M,428.86 - 576.94,6.31,1.65,1.65,428.86,576.94,148.08,Sell
4,BAC,Bank of America Corp,4.28%,46.29,-0.01,-0.03%,21.19 M,32.35 - 48.08,4.28,21.19,21.19,32.35,48.08,15.73,Buy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,GL,Globe Life Inc.,0.14%,122.04,-0.05,-0.04%,0.34 M,38.95 - 132.00,0.14,0.34,0.34,38.95,132.00,93.05,Sell
69,ERIE,Erie Indemnity Co A,0.14%,402.68,-0.27,-0.07%,0.12 M,337.58 - 547.00,0.14,0.12,0.12,337.58,547.00,209.42,Sell
70,IVZ,Invesco Ltd,0.12%,18.44,-0.79,-4.11%,3.13 M,14.16 - 19.55,0.12,3.13,3.13,14.16,19.55,5.39,Buy
71,MKTX,MarketAxess Holdings,0.12%,220.41,-0.22,-0.10%,0.28 M,192.42 - 296.68,0.12,0.28,0.28,192.42,296.68,104.26,Sell
72,BEN,Franklin Resources Inc,0.10%,20.86,-1.39,-6.23%,5.93 M,18.83 - 28.61,0.10,5.93,5.93,18.83,28.61,9.78,Buy