In [2]:
import numpy as np
import pandas as pd

In [4]:
# dir(np)

In [5]:
alist = [10,20,30,40,50]

In [7]:
alist + alist

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]

In [8]:
np_a = np.array(alist)
np_a

array([10, 20, 30, 40, 50])

In [9]:
type(np_a)

numpy.ndarray

In [10]:
np_a + 5

array([15, 25, 35, 45, 55])

In [11]:
np_a + np_a

array([ 20,  40,  60,  80, 100])

In [14]:
np_a[0] = 100.99

In [15]:
np_a

array([100,  20,  30,  40,  50])

In [16]:
blist = [[10,20,30],[40,50,60],[70,80,90]]
blist

[[10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [17]:
np_2 = np.array(blist)

In [18]:
np_2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [21]:
np_2.ndim

2

In [22]:
np_a.ndim

1

In [23]:
np_2.shape

(3, 3)

In [24]:
type(np_2)

numpy.ndarray

In [25]:
np_2.dtype

dtype('int64')

In [26]:
np_2.size

9

In [27]:
np_2.itemsize

8

In [28]:
np_2.nbytes

72

In [29]:
np_2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [30]:
# [start : stop , start : stop]

In [33]:
np_2[0:2,  1:]

array([[20, 30],
       [50, 60]])

In [36]:
np_2[1:2, 0:2]

array([[40, 50]])

In [37]:
np_2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [43]:
new = np_2.copy()

In [44]:
new[0,0] = 1000

In [45]:
np_2

array([[100,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90]])

In [47]:
np_a
sum(np_a)

240

In [49]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)

37.3 ms ± 3.22 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [50]:
big_array = np.random.rand(1000000)
%timeit np.sum(big_array)

197 µs ± 12.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [51]:
sum(np_2)

array([210, 150, 180])

In [52]:
np.sum(np_2)

540

In [53]:
np_2.sum()

540

In [54]:
np_2.max()

100

In [55]:
alist

[10, 20, 30, 40, 50]

In [58]:
s = pd.Series(alist)
s.index

RangeIndex(start=0, stop=5, step=1)

In [59]:
s.values

array([10, 20, 30, 40, 50])

In [63]:
# s[0] = 100.99

In [65]:
s + 5

0    105.99
1     25.00
2     35.00
3     45.00
4     55.00
dtype: float64

In [66]:
s + s

0    201.98
1     40.00
2     60.00
3     80.00
4    100.00
dtype: float64

In [67]:
s.ndim

1

In [68]:
s.shape

(5,)

In [69]:
s.dtype

dtype('float64')

In [70]:
df = pd.DataFrame()

In [72]:
# help(pd.DataFrame)

In [73]:
df

Empty DataFrame
Columns: []
Index: []

In [74]:
df["Stock"] = ["MSFT","AAPL","IBM","ORCL"]

In [75]:
df["Price"] = [260.99, 210.00, 115.00, 56.00]

In [77]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [78]:
df.columns

Index(['Stock', 'Price'], dtype='object')

In [79]:
df.values

array([['MSFT', 260.99],
       ['AAPL', 210.0],
       ['IBM', 115.0],
       ['ORCL', 56.0]], dtype=object)

In [81]:
df.ndim

2

In [82]:
df.shape

(4, 2)

In [86]:
df.dtypes

Stock     object
Price    float64
dtype: object

In [88]:
df["Stock"]

0    MSFT
1    AAPL
2     IBM
3    ORCL
Name: Stock, dtype: object

In [93]:
df["Price"]

0    260.99
1    210.00
2    115.00
3     56.00
Name: Price, dtype: float64

In [116]:
a = ["Price", "Amnt"]
df[["Amnt","Price"]]

       Amnt   Price
Stock
MSFT    100  260.99
AAPL    200  210.00
IBM     300  115.00
ORCL    400   56.00

In [99]:
df["Amnt"] = [100, 200,300,400]

In [102]:
df["Total"] = df["Price"] * df["Amnt"]

In [104]:
df.index = df["Stock"]

In [111]:
df.drop("Stock", axis=1, inplace=True)

In [112]:
df

        Price  Amnt    Total
Stock
MSFT   260.99   100  26099.0
AAPL   210.00   200  42000.0
IBM    115.00   300  34500.0
ORCL    56.00   400  22400.0

In [117]:
# loc vs iloc
# loc - labels
# iloc - index loc

In [122]:
df.loc["AAPL":"IBM", "Amnt":"Total"]

       Amnt    Total
Stock
AAPL    200  42000.0
IBM     300  34500.0

In [125]:
df[["Amnt","Total"]].loc["AAPL":"IBM"]

       Amnt    Total
Stock
AAPL    200  42000.0
IBM     300  34500.0

In [123]:
df.iloc[1:3, 1:]

       Amnt    Total
Stock
AAPL    200  42000.0
IBM     300  34500.0

In [128]:
df.reset_index(inplace=True)

In [129]:
df

  Stock   Price  Amnt    Total
0  MSFT  260.99   100  26099.0
1  AAPL  210.00   200  42000.0
2   IBM  115.00   300  34500.0
3  ORCL   56.00   400  22400.0

In [131]:
condition = df["Price"] < 100
df[condition]

  Stock  Price  Amnt    Total
3  ORCL   56.0   400  22400.0

In [132]:
df[ df["Price"] < 100 ]

  Stock  Price  Amnt    Total
3  ORCL   56.0   400  22400.0

In [138]:
max_total = df["Total"].max()
max_total_condition = df["Total"] == max_total
df[max_total_condition][["Stock","Total"]]

  Stock    Total
1  AAPL  42000.0

In [139]:
df[df["Total"]==df["Total"].max()]

  Stock  Price  Amnt    Total
1  AAPL  210.0   200  42000.0

In [140]:
# find stock with lowest amount of shares
min_amnt = df["Amnt"].min()
min_total_condition = df["Amnt"] == min_amnt
df[min_total_condition][["Stock", "Amnt"]]

  Stock  Amnt
0  MSFT   100